name = "gcsrv-pack"
author = "RedstoneWizard08"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de1114ab8b3d507112cca3566365f02989b36c5427f104d4ea91b7bfa0bddfa1"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
