name = "gcsrv-pack"
author = "RedstoneWizard08"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4464ffe1c2135c447f777ea5e8a235e328bce8be6ae67bff24501a39461dd982"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
