name = "gcsrv-pack"
author = "RedstoneWizard08"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b72e994416fb67e8deebc36bdb3789b0e359ab4c5e5d7ece9438714ac94bf344"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
