name = "gcsrv-pack"
author = "RedstoneWizard08"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56e5c10c36258181cdfc3dc01fb7b174874e6da06f019726af140a0a9748bc2c"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
