name = "gcsrv-pack"
author = "RedstoneWizard08"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e251ed6a6058335a1a59a5383d82f94ebb03893d4f25f8deedba94e06ad7eed0"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
